"""Añadir columna category al modelo Recipe

Revision ID: 2dfbb51459a9
Revises: c06268c2bfec
Create Date: 2025-02-05 02:31:07.534748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfbb51459a9'
down_revision: Union[str, None] = 'c06268c2bfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_recipes_category'), 'recipes', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_category'), table_name='recipes')
    op.drop_column('recipes', 'category')
    # ### end Alembic commands ###
