"""Eliminar columnas innecesarias

Revision ID: c06268c2bfec
Revises: 25e5c09e3420
Create Date: 2025-01-30 18:45:56.252843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06268c2bfec'
down_revision: Union[str, None] = '25e5c09e3420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_column1')
    op.drop_column('users', 'new_column2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_column2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('new_column1', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
